# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: demo-hosts

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

- script: |
    mvn -f simplewebapp/pom.xml clean package
  displayName: 'maven-build'

- script: |
    cp -R simplewebapp/target/simplewebapp.war /var/lib/tomcat/webapps
  displayName: 'Deploy'